"""users_words_table_edited

Revision ID: 09db67b2605c
Revises: 85bb80929a91
Create Date: 2021-11-21 01:52:10.788483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09db67b2605c'
down_revision = '85bb80929a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
