"""2nd migrate

Revision ID: 31bfaf4516d6
Revises: 9996b1405b2b
Create Date: 2021-11-25 14:27:05.524807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bfaf4516d6'
down_revision = '9996b1405b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
