"""Mixins added to assiciation table

Revision ID: 41d68e52dc1e
Revises: bd1b7aae2748
Create Date: 2021-11-28 22:08:44.337383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d68e52dc1e'
down_revision = 'bd1b7aae2748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_associationtables', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_associationtables', 'created_at')
    # ### end Alembic commands ###
