"""extend_existing_deleted

Revision ID: 489ddcfec71e
Revises: 741eb72f3922
Create Date: 2021-11-21 02:17:39.298885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489ddcfec71e'
down_revision = '741eb72f3922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
