"""autoincrement deleted from id database

Revision ID: 53445e203e87
Revises: 41d68e52dc1e
Create Date: 2021-11-28 22:21:29.794677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53445e203e87'
down_revision = '41d68e52dc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
