"""new_migration

Revision ID: 540c801d7a47
Revises: d19aba4fb05d
Create Date: 2021-11-21 02:07:07.216236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540c801d7a47'
down_revision = 'd19aba4fb05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
