"""str and repr added to User and Word

Revision ID: 64690adccb43
Revises: aa0d667d063f
Create Date: 2021-11-28 21:34:30.848194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64690adccb43'
down_revision = 'aa0d667d063f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
