"""database.id autoincrement added

Revision ID: 659f6cbe2661
Revises: 892363a7fe5f
Create Date: 2021-11-28 00:29:34.547701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659f6cbe2661'
down_revision = '892363a7fe5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
