"""extend_existing_added

Revision ID: 741eb72f3922
Revises: 540c801d7a47
Create Date: 2021-11-21 02:12:49.619370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741eb72f3922'
down_revision = '540c801d7a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
