"""somenewmigration

Revision ID: 805447b71f77
Revises: b35336fb3cf1
Create Date: 2021-11-21 02:03:28.976332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805447b71f77'
down_revision = 'b35336fb3cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
