"""Create tables

Revision ID: 85bb80929a91
Revises: 
Create Date: 2021-11-20 02:05:13.989906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bb80929a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_words',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), server_default='', nullable=False),
    sa.Column('translation', sa.String(length=120), server_default='', nullable=False),
    sa.Column('synonym', sa.String(length=120), server_default='', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_users_words_association_table',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['bot_words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_users_words_association_table')
    op.drop_table('bot_words')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
