"""test1

Revision ID: 87998d1a3cfb
Revises: 64690adccb43
Create Date: 2021-11-28 22:02:23.638697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87998d1a3cfb'
down_revision = '64690adccb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
