"""database.id default added

Revision ID: 892363a7fe5f
Revises: 9daf1a29bf2c
Create Date: 2021-11-28 00:27:02.834241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892363a7fe5f'
down_revision = '9daf1a29bf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
