"""3rd migrate

Revision ID: 8cd6da4c671c
Revises: 31bfaf4516d6
Create Date: 2021-11-25 14:30:07.980516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd6da4c671c'
down_revision = '31bfaf4516d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
