"""back_populates_added

Revision ID: 8d2529e71670
Revises: be395676dd73
Create Date: 2021-11-21 02:46:35.611015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2529e71670'
down_revision = 'be395676dd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
