"""synonims_deleted

Revision ID: 9b5902781c3f
Revises: 02745bd63046
Create Date: 2021-11-21 21:19:32.996980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5902781c3f'
down_revision = '02745bd63046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_words', 'synonym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_words', sa.Column('synonym', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
