"""database.id get autoincrement

Revision ID: 9daf1a29bf2c
Revises: b5278880c7ff
Create Date: 2021-11-26 09:36:45.461658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daf1a29bf2c'
down_revision = 'b5278880c7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
