"""users_words_class

Revision ID: b35336fb3cf1
Revises: 09db67b2605c
Create Date: 2021-11-21 01:56:43.643917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35336fb3cf1'
down_revision = '09db67b2605c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
