"""associationTable.id get autoincrement

Revision ID: b5278880c7ff
Revises: 8cd6da4c671c
Create Date: 2021-11-26 09:21:00.868627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5278880c7ff'
down_revision = '8cd6da4c671c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
