"""last upgrade

Revision ID: bd1b7aae2748
Revises: 87998d1a3cfb
Create Date: 2021-11-28 22:03:54.045741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1b7aae2748'
down_revision = '87998d1a3cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
