"""User_edited_1word

Revision ID: be395676dd73
Revises: 0128056a73b2
Create Date: 2021-11-21 02:39:27.951331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be395676dd73'
down_revision = '0128056a73b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
