"""somenewmigration1

Revision ID: d19aba4fb05d
Revises: 805447b71f77
Create Date: 2021-11-21 02:05:44.842221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19aba4fb05d'
down_revision = '805447b71f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_users', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_users', 'lastname')
    # ### end Alembic commands ###
